language: node_js
node_js:
  - "5"
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test-cov
after_script:
  - cat ./coverage/lcov.info | coveralls;
