version: 0.0.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - npm install npm -g
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off

deploy:
  release: GLBrowser-win-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: Iw1LOHpMR1UmPK3xaxVMow6d9FTgIIhkSEC4zqmh4kw423OYj1yyvYFwPG1N39sI
  artifact: dist\win\*.exe
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
